// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4F2V_POKrdGsxPuWooICjzO1ZU1IgH4',
    appId: '1:490528778312:web:02b036c7ac5993fdb7907d',
    messagingSenderId: '490528778312',
    projectId: 'antam-de662',
    authDomain: 'antam-de662.firebaseapp.com',
    storageBucket: 'antam-de662.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcYztcwR-Lqryfqrz2tEQmi2O3stZ10mM',
    appId: '1:490528778312:android:d072e0c39f812452b7907d',
    messagingSenderId: '490528778312',
    projectId: 'antam-de662',
    storageBucket: 'antam-de662.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2O8fpytnyD6VLJLso0yxeXHYlNgY-SwE',
    appId: '1:490528778312:ios:83496e1c0da40954b7907d',
    messagingSenderId: '490528778312',
    projectId: 'antam-de662',
    storageBucket: 'antam-de662.firebasestorage.app',
    iosBundleId: 'com.example.duanAntam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2O8fpytnyD6VLJLso0yxeXHYlNgY-SwE',
    appId: '1:490528778312:ios:83496e1c0da40954b7907d',
    messagingSenderId: '490528778312',
    projectId: 'antam-de662',
    storageBucket: 'antam-de662.firebasestorage.app',
    iosBundleId: 'com.example.duanAntam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG4F2V_POKrdGsxPuWooICjzO1ZU1IgH4',
    appId: '1:490528778312:web:8eb84d13bf8fafd7b7907d',
    messagingSenderId: '490528778312',
    projectId: 'antam-de662',
    authDomain: 'antam-de662.firebaseapp.com',
    storageBucket: 'antam-de662.firebasestorage.app',
  );
}
